language: node.js
node.js: 
  - 12.21.0

jdk:
  - oraclejdk8
addon:
  sonarcloud: true
script:
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=fedemos123 -Dsonar.projectKey=Calculadora-tpi -Dsonar.sources='./app' -X